_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  FCOS:
    POST_NMS_TOPK_TEST: 500
    POST_NMS_TOPK_TRAIN: 500
    INFERENCE_TH_TEST: 0.4
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  IMS_PER_BATCH: 4
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
OUTPUT_DIR: "output/fcos/R_50_1x"
